[Done] Ability to drag item into LONG LIST
DaftDoris/newsdesk pull request #155
Opened 2022-04-29 11:35 UTC by bhavinsen

2022-04-29 15:17 UTC, chrisns requested changes
indentation, and other linting errors
run `eslint .` and `npm run build` and fix issues, then I'll review the actual change

2022-05-02 09:43 UTC, chrisns requested changes
appears to be built on top of #154 so either that'll need to be merged before this can be, or this will need to be refactored to be independent

2022-05-02 09:43 UTC, chrisns commented on src/pages/Home.vue
> +	const draggedLongList = (x: number, y: number, item: Item, podcastId: string) => {
indentation?

2022-05-05 11:19 UTC, bhavinsen commented on src/pages/Home.vue
> +	const draggedLongList = (x: number, y: number, item: Item, podcastId: string) => {
No

2022-05-06 06:19 UTC, chrisns requested changes

2022-05-06 06:19 UTC, chrisns commented on src/pages/Home.vue
> +	const draggedLongList = (x: number, y: number, item: Item, podcastId: string) => {
Indentation still off

2022-05-06 06:19 UTC, chrisns commented on src/pages/Home.vue
> +  document.elementFromPoint(x, y)?.attributes["item-slot"]?.value)
indentation here too is off

2022-05-06 06:19 UTC, chrisns commented on src/pages/Home.vue
> +    const slotItem =itemStore.getList
```suggestion
    const slotItem = itemStore.getList
```

2022-05-06 06:20 UTC, chrisns commented
Looks like there's basic code consistency errors that eslint should probably fix for you

2022-05-06 22:45 UTC, merged