copied slot text
DaftDoris/newsdesk pull request #221
Opened 2022-05-13 10:29 UTC by bhavinsen

Fixed #113

2022-05-16 07:46 UTC, chrisns approved these changes

2022-05-16 07:46 UTC, chrisns commented
@mrjamieeast have you tried this?

2022-05-18 13:43 UTC, chrisns requested changes
please write a test for this

2022-05-19 04:28 UTC, mrjamieeast commented
This pastes the results upside down (bottom to top) rather than the way they appear on the page

2022-05-19 06:06 UTC, mrjamieeast commented
This works for me now. thanks

2022-05-23 13:09 UTC, chrisns requested changes

2022-05-23 13:09 UTC, chrisns commented on cypress/integration/podcasts.spec.js
> +  })
you should be able to check the clipboard with something like https://egghead.io/blog/handling-copy-and-paste-in-cypress

2022-05-26 07:28 UTC, chrisns approved these changes

2022-05-26 07:28 UTC, merged