SCRIPT4: Create CLIP field #243, SCRIPT 5: Create ability to add multiple clip fields within SCRIPT item #244 -- yg
DaftDoris/newsdesk pull request #378
Opened 2022-06-28 15:51 UTC by ArindamReact

As per the issue, I've done the following changes

1. created one common component for the Clip field
2. added some tailwind CSS using https://github.com/apply in CSS
3. also as per the discussion on call I've added one text area and added below the Clip field on click of the sound button
4. also there is an error regarding ss-furniture in this class, so I've removed it.

2022-06-28 17:29 UTC, chrisns requested changes

2022-06-28 17:29 UTC, chrisns commented on src/components/molecules/Cards/ItemCard.vue
> +// }
```suggestion
```
no need to commit commented code

2022-06-29 04:53 UTC, mrjamieeast approved these changes

2022-06-29 04:56 UTC, chrisns requested changes

2022-06-29 04:56 UTC, chrisns commented on src/components/Script.vue
> +  console.log(items, '=========>')
```suggestion
```

2022-06-29 16:16 UTC, chrisns approved these changes
@mrjamieeast please can you check this functionality works as expected?

2022-06-30 10:17 UTC, mrjamieeast approved these changes

2022-06-30 10:17 UTC, mrjamieeast approved these changes

2022-06-30 11:29 UTC, merged