PODCAST PAGE - Display podcast title underneath thumbnail #324
DaftDoris/newsdesk pull request #438
Opened 2022-07-27 19:50 UTC by ArindamReact

I've made the changes according to metion in ticket and made the change to Selectpodcast.vue.

2022-07-29 04:59 UTC, mrjamieeast commented
Please change Font to Bree Serif regular as per the design

2022-08-01 07:02 UTC, mrjamieeast approved these changes

2022-08-01 07:55 UTC, mrjamieeast commented
hi @ArindamReact cloudflare build failed

2022-08-01 20:51 UTC, chrisns requested changes
add a test

2022-08-02 05:58 UTC, ArindamReact commented
> add a test

There is no functionality so no test required, there is only text addition.

2022-08-02 06:32 UTC, chrisns commented
> > add a test
> 
> 
> 
> There is no functionality so no test required, there is only text addition.

Assert that the expected text is actually where you expect it to be, proving that it's mapped from the store through to the view correctly?

2022-08-05 07:44 UTC, chrisns approved these changes

2022-08-05 16:00 UTC, chrisns approved these changes

2022-08-05 17:58 UTC, chrisns requested changes
Not sure why you needed to change the package lock. Also fix indentation

2022-08-05 17:58 UTC, chrisns commented on cypress/e2e/podcasts.cy.js
> +  })
Indentation?

2022-08-05 18:00 UTC, ArindamReact commented
> Not sure why you needed to change the package lock. Also fix indentation

because new packages have added in main, and build is failing with current one

2022-08-05 18:11 UTC, chrisns commented
> > Not sure why you needed to change the package lock. Also fix indentation
> 
> 
> 
> because new packages have added in main, and build is failing with current one

That's very vague. So you're saying you've reverted updates in main in order to say this is done, without even providing context, perhaps some of those fixes included security fixes.
Please make this change work with the upstream

2022-08-05 18:16 UTC, ArindamReact commented
> > > Not sure why you needed to change the package lock. Also fix indentation
> > 
> > 
> > because new packages have added in main, and build is failing with current one
> 
> That's very vague. So you're saying you've reverted updates in main in order to say this is done, without even providing context, perhaps some of those fixes included security fixes. Please make this change work with the upstream

No, I just merge main in my branch because it has conflicts, I've resolved then pushed on PR. Then build fails due to packages are outdated. Then I've updated the package lock using npm install and pushed

2022-08-09 11:53 UTC, mrjamieeast approved these changes

2022-08-09 11:56 UTC, chrisns approved these changes

2022-08-09 13:51 UTC, merged