Delete from inbox
DaftDoris/newsdesk pull request #509
Opened 2022-08-20 11:36 UTC by ArindamReact

2022-08-21 18:21 UTC, chrisns requested changes
test

2022-08-22 05:08 UTC, ArindamReact commented
According to sonar, the test is already written

2022-08-22 06:06 UTC, mrjamieeast commented
@chrisns good to proceed?

2022-08-24 05:05 UTC, mrjamieeast commented
@ArindamReact updating branch caused failures - please check

2022-08-24 08:30 UTC, chrisns approved these changes

2022-08-24 08:30 UTC, merged